apiVersion: v1
kind: Pod
metadata:
  name: search-pod
  namespace: p-go-search
  labels:
    app: search-persona
spec:
  nodeSelector:
    workload: search
  containers:
    - name: search-container
      image: danysoftdev/p-go-search:latest
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: mongo-search-secret