apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: search-replicaset
  namespace: p-go-search
  labels:
    app: search-persona
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-persona
  template:
    metadata:
      labels:
        app: search-persona
    spec:
      nodeSelector:
        workload: search
      containers:
        - name: search-container
          image: danysoftdev/p-go-search:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mongo-search-secret